#!/bin/bash
# carbontoolkit
# Created by Andrea Rebora (@AndreaRebora01)

INSTALL_DIR="/usr/share/carbontoolkit"
service postgresql start

if [ -f ~/.carbontoolkit.conf ]; then
  source ~/.carbontoolkit.conf
else
  cp $INSTALL_DIR/carbontoolkit.conf ~/.carbontoolkit.conf 2> /dev/null
  source ~/.carbontoolkit.conf
fi

echo ""
echo "                        _                   __                  __         __  __    "
echo "     _____   __  ______| |__    ____   ____/  |__  ____   ____ |  |  __  _|__|/  |_  "
echo "   _/ ___/  /__\ \_  __ \ __ \ /    \ /    \   __\/    \ /    \|  | |  |/ /  \   __\ "
echo "   \  \___ / __ \ |  | \/ \_\ (  <>  )   |  \  | (  <>  |  <>  )  |_|    <|  ||  |   "
echo "    \_____/_/  \_\|__|  |_____/\____/|___|__/__|  \____/ \____/|____/__|__\__||__|   "
echo "                                                                                     "
echo "		Information Gathering and Vulnerability Assessment"
echo "		Version 1.0"
echo "		Created by Andrea Rebora (AndreaRebora01)"
echo ""
tput setaf 1; echo "[Enter the target]"
tput sgr0;
read TARGET
echo ""
tput setaf 1; echo "[Running Whois]"
tput sgr0;
echo ""
whois $TARGET
echo ""
tput setaf 1; echo "[Running NsLookup]"
tput sgr0;
echo ""
nslookup $TARGET
echo ""
tput setaf 1; echo "[Running Dnsenum]"
tput sgr0;
echo ""
dnsenum $TARGET -f /usr/share/wordlists/seclists/Discovery/DNS/dns-Jhaddix.txt --noreverse -v -s 15
echo ""
tput setaf 1; echo "[Running Nmap]"
tput sgr0;
echo ""
nmap -sS --open -Pn -v $TARGET
echo ""
nmap -Pn -sU -sV -A -v --script=/usr/share/nmap/scripts/vulscan/vulscan.nse,/usr/share/nmap/scripts/vulners -p 22,80,443,161,162 $TARGET
echo ""
tput setaf 1; echo "[Running Nikto]"
tput sgr0;
echo ""
nikto -host http://$TARGET
echo ""
nikto -host https://$TARGET
echo ""
tput setaf 1; echo "[Running TheHarvester]"
tput sgr0;
echo ""
theHarvester -d $TARGET -b all
echo ""
tput setaf 1; echo "[Running Metagoofil]"
tput sgr0;
echo ""
python $INSTALL_DIR/metagoofil/metagoofil.py -d $TARGET -t ALL -l 500 -n 100 -o /root/Desktop -f $TARGET_metagoofil.html
echo ""
tput setaf 1; echo "[Running DNSRecon]"
tput sgr0;
echo ""
dnsrecon -d $TARGET -a -s -g -b -k -w -z -D /usr/share/wordlists/seclists/Discovery/DNS/dns-Jhaddix.txt
echo ""
tput setaf 1; echo "[Running Wafw00f]"
tput sgr0;
echo ""
wafw00f http://$TARGET -v -a
echo ""
tput setaf 1; echo "[Running WAFNinja]"
tput sgr0;
echo ""
python $INSTALL_DIR/WAFNinja/wafninja.py bypass -u "http://$TARGET/index.php" -p "Name=PAYLOAD&Submit=Submit" -c "phpsessid=value" -t xss
echo ""
python $INSTALL_DIR/WAFNinja/wafninja.py fuzz -u "http://$TARGET/index.php?id=FUZZ" -c "phpsessid=value" -t xss
echo ""
tput setaf 1; echo "[Running Wget commands. Please be patient.]"
tput sgr0;
echo""
mkdir Findings
mv Findings Desktop
wget http://$TARGET/robots.txt -o /root/Desktop/Findings/robotshttp.txt
wget https://$TARGET/robots.txt -o /root/Desktop/Findings/robotshttps.txt
wget -q http://www.intodns.com/$TARGET -o /root/Desktop/Findings/intodns.txt
wget -qO -T 1 --connect-timeout=15 --read-timeout=15 --tries=2 http://$TARGET -o /root/Desktop/Findings/a.txt
wget -qO -T 1 --connect-timeout=15 --read-timeout=15 --tries=2 https://$TARGET -o /root/Desktop/Findings/d.txt
curl --connect-timeout 15 --max-time 15 -I -s -R http://$TARGET -o /root/Desktop/Findings/b.txt
curl --connect-timeout 15 -s -R -L http://$TARGET -o /root/Desktop/Findings/c.txt
curl --connect-timeout 15 --max-time 15 -I -s -R https://$TARGET -o /root/Desktop/Findings/e.txt
curl --connect-timeout 15 -s -R -L https://$TARGET -o /root/Desktop/Findings/f.txt
curl -sX GET "http://index.commoncrawl.org/CC-MAIN-2018-22-index?url=*.$TARGET&output=json" -o /root/Desktop/Findings/commoncrawl.txt
curl -sX GET "http://web.archive.org/cdx/search/cdx?url=*.$TARGET/*&output=text&fl=original&collapse=urlkey" -o /root/Desktop/Findings/archive.txt
curl -sX GET "http://api.hackertarget.com/pagelinks/?q=https://$TARGET" -o /root/Desktop//Findings/hackertarget.txt
curl -s https://www.ultratools.com/tools/ipWhoisLookupResult\?ipAddress\=$TARGET -o /root/Desktop//Findings/ultratools.txt
curl -s https://www.email-format.com/d/$TARGET -o /root/Desktop/Findings/email-format.txt
curl -fsSL "https://dns.bufferover.run/dns?q=.$TARGET" grep $TARGET -o /root/Desktop/Findings/bufferover.txt
curl -s https://crt.sh/?q=%25.$TARGET -o /root/Desktop//Findings/crt.txt
curl --connect-timeout 15 --max-time 15 -I -s -R -X OPTIONS http://$TARGET -o /root/Desktop/Findings/grep1.txt | grep Allow\:
curl --connect-timeout 15 --max-time 15 -I -s -R -X OPTIONS https://$TARGET -o /root/Desktop/Findings/grep2.txt | grep Allow\:
curl -s "https://api.hunter.io/v2/domain-search?domain=$TARGET&api_key=$HUNTERIO_KEY" curl --connect-timeout 15 --max-time 15 -I -s -R -X OPTIONS https://$TARGET -o /root/Desktop/Findings/grep3.txt | egrep "name|value|domain|company|uri|position|phone"
curl -s -L --data "ip=$TARGET" https://2ip.me/en/services/information-service/provider-ip\?a\=act curl --connect-timeout 15 --max-time 15 -I -s -R -X OPTIONS https://$TARGET -o /root/Desktop/Findings/grep4.txt | grep -o -E '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}/[0-9]{1,2}'
echo ""
tput setaf 1; echo "[Running CutyCapt]"
tput sgr0;
echo ""
cutycapt --url=http://$TARGET --out=/root/Desktop/$TARGET-port80.jpg --insecure
echo ""
cutycapt --url=https://$TARGET --out=/root/Desktop/$TARGET-port443.jpg --insecure
echo ""
tput setaf 1; echo "[Running webscreenshot]"
tput sgr0;
echo ""
python2 $INSTALL_DIR/webscreenshot.py -r chromium http://$TARGET:80
echo ""
python2 $INSTALL_DIR/webscreenshot.py -r chromium https://$TARGET:443
echo ""
tput setaf 1; echo "[Running XssPy]"
tput sgr0;
echo ""
python $INSTALL_DIR/XssPy.py -u $TARGET -e -v
echo ""
tput setaf 1; echo "[Running WhatWeb]"
tput sgr0;
echo ""
ruby $MODULES_DIR/WhatWeb/whatweb $TARGET -a 3 -v
echo ""
tput setaf 1; echo "[Running WAScan]"
tput sgr0;
echo ""
python $MODULES_DIR/WAScan/wascan.py -u $TARGET -s 5 -v 
echo ""
tput setaf 1; echo "[Running WPScan]"
tput sgr0;
echo ""
wpscan --url http://$TARGET -e u
echo ""
tput setaf 1; echo "[Running WPSeku]"
tput sgr0;
echo ""
python $INSTALL_DIR/WPSeku/wpseku.py -t http://$TARGET
echo ""
tput setaf 1; echo "[Running droopescan (WordPress)]"
tput sgr0;
echo ""
droopescan scan wordpress -u http://$TARGET
echo ""
tput setaf 1; echo "[Running droopescan (Joomla)]"
tput sgr0;
echo ""
droopescan scan joomla -u http://$TARGET
echo ""
tput setaf 1; echo "[Running droopescan (Drupal)]"
tput sgr0;
echo ""
droopescan scan drupal -u http://$TARGET
echo ""
tput setaf 1; echo "[Running droopescan (Silverstripe)]"
tput sgr0;
echo ""
droopescan scan silverstripe -u http://$TARGET
echo ""
tput setaf 1; echo "[Running droopescan (Moodle)]"
tput sgr0;
echo ""
droopescan scan moodle -u http://$TARGET
echo ""
tput setaf 1; echo "[Running sslscan]"
tput sgr0;
echo ""
sslscan --no-failed $TARGET
echo ""
tput setaf 1; echo "[Running sslyze]"
tput sgr0;
echo ""
sslyze --regular --hide_rejected_ciphers --http_headers --slow_connection $TARGET
echo ""
tput setaf 1; echo "[Running a2sv]"
tput sgr0;
echo""
python $MODULES_DIR/a2sv/a2sv.py -t $TARGET
echo ""
tput setaf 1; echo "[Running Sublist3r]"
tput sgr0;
echo ""
sublist3r -d $TARGET -b -vvv
echo ""
tput setaf 1; echo "[Running dirsearch]"
tput sgr0;
echo ""
dirsearch -u $TARGET -e html,htm,gif,jpg,png,cgi,pl,js,java,class,php,php3,shtm,shtml,asp,cfm,cfml
echo ""
dirsearch -u http://$TARGET -w /usr/share/wordlists/seclists/Discovery/Web-Content/big.txt  -e * --random-agents
echo ""
dirsearch -u http://$TARGET -w /usr/share/wordlists/seclists/Discovery/Web-Content/big.txt -x 400,403,404,405,406,429,502,503,504 -F -e *
echo ""
dirsearch -u https://$TARGET -w /usr/share/wordlists/seclists/Discovery/Web-Content/big.txt -x 400,403,404,405,406,429,502,503,504 -F -e *
echo ""
tput setaf 1; echo "[Running wig]"
tput sgr0;
echo ""
python3 $MODULES_DIR/wig/wig.py -d -q http://$TARGET
echo ""
python3 $MODULES_DIR/wig/wig.py -d -q https://$TARGET
echo ""
tput setaf 1; echo "[Running BlackWidow]"
tput sgr0;
echo ""
blackwidow -u http://$TARGET:80 -l 5 -v y
echo ""
blackwidow -u https://$TARGET:443 -l 5 -v y
echo ""
tput setaf 1; echo "[Running Gobuster]"
tput sgr0;
echo ""
gobuster -u http://$TARGET -w /usr/share/wordlists/seclists/Discovery/Web-Content/common.txt -e
echo ""
gobuster -u https://$TARGET -w /usr/share/wordlists/seclists/Discovery/Web-Content/common.txt -e
echo ""
tput setaf 1; echo "[Running URLCrazy]"
tput sgr0;
echo ""
urlcrazy $TARGET
echo ""
tput setaf 1; echo "[Running Goohak]"
tput sgr0;
echo ""
goohak $TARGET
echo ""
amass enum -ip -d $TARGET
echo ""
tput setaf 1; echo "[Running subfinder]"
tput sgr0;
echo ""
subfinder -d $TARGET -v
echo ""
tput setaf 1; echo "[Running dnscan]"
tput sgr0;
echo ""
python $MODULES_DIR/dnscan/dnscan.py -d $TARGET -w /usr/share/carbontoolkit/modules/dnscan/subdomains-10000.txt
echo ""
tput setaf 1; echo "[Running Censys]"
tput sgr0;
echo ""
python $MODULES_DIR/censys-subdomain-finder/censys_subdomain_finder.py --censys-api-id $CENSYS_APP_ID --censys-api-secret $CENSYS_API_SECRET $TARGET | egrep "\-" | awk '{print $2}'
echo ""
tput setaf 1; echo "[Running altdns]"
tput sgr0;
echo ""
echo "$TARGET" >> /root/Desktop/$TARGET.txt
altdns -i /root/Desktop/$TARGET.txt -w /usr/share/wordlists/seclists/Discovery/DNS/fierce-hostlists.txt -o /root/Desktop/$TARGET-altdns.txt
echo ""
tput setaf 1; echo "[Running massdns]"
tput sgr0;
echo ""
massdns -r /pentest/intelligence-gathering/massdns/lists/resolvers.txt /root/Desktop/$TARGET.txt
echo ""
tput setaf 1; echo "[Running spoofcheck]"
tput sgr0;
echo ""
spoofcheck $TARGET
echo ""
tput setaf 1; echo "[Running BruteX]"
tput sgr0;
echo ""
brutex $TARGET
echo ""
tput setaf 1; echo "[Done]"
tput sgr0;
echo ""
